Resize image
yelenskaya/celerySkillup pull request #1
Opened 2023-01-26 14:33 UTC by yelenskaya

2023-01-26 16:24 UTC, DenysMoskalenko requested changes

2023-01-26 16:24 UTC, DenysMoskalenko commented on app/image_transformation.py
> +    file_extension = file_name.split('.')[-1]
os.path.splitext

2023-01-26 16:24 UTC, DenysMoskalenko commented on app/image_transformation.py
> +    if file_extension not in SUPPORTED_IMAGE_EXTENSIONS:
frozenset

2023-01-26 16:24 UTC, DenysMoskalenko commented on app/routes.py
> +router = APIRouter(prefix='/image', tags=['image'])
по ресту обычно путь делают во множественном числе.

2023-01-26 16:24 UTC, DenysMoskalenko commented on app/s3_manager.py
> +def does_file_exist(resource: ServiceResource, bucket: str, object_key: str) -> bool:
Разве нам это нужно?

2023-01-26 16:24 UTC, DenysMoskalenko commented on app/s3_manager.py
> +    return f'single/{file_id}/original/{file_name}'
Почему не сделать другой бакет для оригинальных изображений. и использовать просто uuid как путь.
Этот пакет может быть настроен на автоочистку.
Так-же для ресайзнутых картинок могут быть настроены разные лайвсайкл рулы, версии, шифрование и прочие вещи, которые для важных элементов нужны, в том случае как для оригинальны йтебе ничгео этого не надо. "потеряется и потеряется". (Так-же для такого бакета можно изменить его тип, например на S3 One Zone-IA, который секономит деняг, но сюда пока не углубляйся. Суть в разделении - никогда не мешай что-то не важное с чем-то важным)

2023-01-26 16:29 UTC, DenysMoskalenko commented on .flake8
> +application-import-names = app
синхронизацию настроек на профиле не ставила? советую

2023-01-26 16:30 UTC, yelenskaya commented on app/dependencies.py
> +def create_celery():
Не придумала, куда класть

2023-01-27 12:11 UTC, DenysMoskalenko commented on app/routes.py
> +        _settings: Settings = Depends(get_settings),
а зачем _settings с нижним подчеркиванием делаешь?

2023-01-27 12:11 UTC, DenysMoskalenko commented on app/routes.py
> +    upload_file_object(
Может добави какую-нибудь лоигику поверх метода upload_file_object.
Будет у тебя какой-то client.upload_single_object.
Сам client будет инкапсулировать в себе построение ключей и работу с низкоуровневой boto. В таком случае тебе не прийдется думать во всей программе про то, чтоб не забыть вызвать get_original_image_key и тд.

Но в рамкой этой задачи по СЕЛЕРИ, на это можно забить

2023-01-27 12:11 UTC, DenysMoskalenko commented on app/tasks.py
> +    _settings = get_settings()
в чем суть нижнего подчеркивания тут? что ты этим хочешь сказать?

2023-01-27 13:13 UTC, yelenskaya commented on app/tasks.py
> +    _settings = get_settings()
блин. я откуда-то запомнила, что был ворнинг про shadowing переменной, и везде его из-за этого пытаюсь не шадовить. уберу

2023-01-27 13:33 UTC, yelenskaya commented on app/routes.py
> +    upload_file_object(
Наверно забью пока

2023-01-27 14:59 UTC, DenysMoskalenko approved these changes

2023-01-27 15:00 UTC, merged

2023-01-27 15:00 UTC, DenysMoskalenko commented on app/routes.py
> +    upload_file_object(
Окей, но это важный момент в продакшн коде. Ты должна выделять такие вот моменты. аля dao, которые мы делали, оборачивая низкоуровневые штуки

2023-01-27 15:15 UTC, yelenskaya commented on app/routes.py
> +    upload_file_object(
Учту, спасибо