Scheduled batch image conversion
yelenskaya/celerySkillup pull request #2
Opened 2023-02-07 14:28 UTC by yelenskaya

2023-02-07 16:33 UTC, DenysMoskalenko requested changes

2023-02-07 16:33 UTC, DenysMoskalenko commented on app/s3_manager.py
> +) -> list:
а список чего мы возвращаем?

2023-02-07 16:33 UTC, DenysMoskalenko commented on app/s3_manager.py
> +        summaries = summaries.limit(max_number)
Получается ты грузишь все обьекты в память? и потом лимитишь?
Это опасно

2023-02-07 16:33 UTC, DenysMoskalenko commented on app/s3_manager.py
> +        if filters:
Нужно ли тебе filters?
По сути у теяб будет только один фильтре на имя папки.
Можно либо начать с простого и не создавать обьект filters
Либо уже делать серьезно - выносить построение фильтров в отдельную функцию и тд.

2023-02-07 16:33 UTC, DenysMoskalenko commented on app/tasks.py
> +    get_object_summaries, S3Prefix,
new line

2023-02-07 16:33 UTC, DenysMoskalenko commented on app/tasks.py
> +             summaries if not summary.key == S3Prefix.BATCH.value]
очень непонятный мне иф как такое получилось?

2023-02-07 16:33 UTC, DenysMoskalenko commented on app/tasks.py
> +    converted_s3_file_path = replace_file_extension(original_s3_file_path, target_format)
почему б не реплейсить расширение прям в функции convert_image.
Получается у тебя логика преобразования живет отдельно от экстеншинов

2023-02-08 09:51 UTC, yelenskaya commented on app/s3_manager.py
> +) -> list:
ObjectSummary, но это тип бото, который вынуть не получается

2023-02-08 09:52 UTC, yelenskaya commented on app/s3_manager.py
> +        summaries = summaries.limit(max_number)
А там по-другому не получается никак, потому что MaxKeys не работает - тот баг что я тебе скидывала: https://github.com/boto/boto3/issues/2186 Но это не объекты - только саммари объектов

2023-02-08 09:52 UTC, yelenskaya commented on app/s3_manager.py
> +        if filters:
Ага, уберу

2023-02-08 09:53 UTC, yelenskaya commented on app/tasks.py
> +             summaries if not summary.key == S3Prefix.BATCH.value]
лист объектов отдает в том числе папку

2023-02-08 09:53 UTC, yelenskaya commented on app/tasks.py
> +    converted_s3_file_path = replace_file_extension(original_s3_file_path, target_format)
Логично, сделаю

2023-02-08 11:26 UTC, DenysMoskalenko commented on app/s3_manager.py
> +) -> list:
точна?(

2023-02-08 11:27 UTC, DenysMoskalenko commented on app/s3_manager.py
> +        summaries = summaries.limit(max_number)
А что имеет в себе Самари обьектов?

2023-02-08 12:14 UTC, yelenskaya commented on app/tasks.py
> +             summaries if not summary.key == S3Prefix.BATCH.value]
Угу - там префикс со слешом (

2023-02-08 12:16 UTC, yelenskaya commented on app/s3_manager.py
> +        summaries = summaries.limit(max_number)
![image](https://user-images.githubusercontent.com/45938314/217527295-7444cb1f-879f-4cd7-8878-ca971ee02cc6.png)
Большого ничего не видела там, метаданные в основном https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#objectsummary

2023-02-08 12:19 UTC, yelenskaya commented on app/s3_manager.py
> +) -> list:
У меня не вышло. Там есть отдельный пекедж для тайпхинтинга в бото https://pypi.org/project/boto3-stubs/ Могу поставить

2023-02-16 11:49 UTC, merged